version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ankona-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x9f7vbigyul8"
s3_prefix = "ankona-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
